apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "quiz-backend.labels" . | nindent 4 }}
  app.kubernetes.io/component: quiz-backend-service
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
  {{- include "quiz-backend.selectorLabels" . | nindent 4 }}
  app.kubernetes.io/component: quiz-backend