apiVersion: v1
kind: Service
metadata:
  name: {{ include "quiz-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quiz-frontend.labels" . | nindent 4 }}
    app.kubernetes.io/component: quiz-frontend-service
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "quiz-frontend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: quiz-frontend
